# .github/workflows/docs.yml
name: Deploy Docs

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**' ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        working-directory: ./docs
        run: npm ci
        
      - name: Build docs
        working-directory: ./docs
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
